name: Task

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */3 * * *"
env:
  PYTHONUTF8: 1

jobs:
  build:
    name: Build
    runs-on: windows-latest
    permissions: 
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Python 3.13.2
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.2"

      - name: Run Script
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -u script.py